spring:
  sleuth:    trace-id128: true
    sampler:      probability: 1.0
  zipkin:
   base-url: http://192.168.99.100:9411/
  application:
   name: convertCurrencyMS
  h2:    console:      enabled: true
      path: /h2
      
server:
  port: 8888
   
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/
     
feign:  hystrix:    enabled: true
    
management:  endpoints:    web:      exposure:        include: '*'
     

   