spring:
  sleuth:
    trace-id128: true
    sampler:
      probability: 1.0
  zipkin:
   base-url: http://192.168.99.100:9411/
  application:    name: conversionFactor
  profiles:    active: dev
  h2:
    console:
      enabled: true
      path: /h2
server:  port: ${PORT:0}

eureka:
  client:    register-with-eureka: true    fetch-registry: true
    serviceUrl:
     defaultZone: http://192.168.99.100:8761/eureka/
  instance:    instance-id: ${spring.application.name}:${random.int}
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true
    metadata-map:
      zone: A
management:
  endpoints:
    web:
      exposure:
        include: '*'