server:
  port: 8761
eureka:
  instance:
    hostname: currencyconverter
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
     defaultZone: http://192.168.99.100:8761/eureka

    