--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: ccfms
    version: v1
  name: ccfms
spec: 
  strategy: # Default, so usually not specified
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1  # specifies the maximum number of Pods that can be created over the desired number of Pods
      maxUnavailable: 25% #specifies the maximum number of Pods that can be unavailable during the update process
  replicas: 1
  selector: 
    matchLabels: 
      app: ccfms
      version: v1
  template: 
    metadata: 
      labels: 
        app: ccfms
        version: v1

    spec: 

      containers: 
        - 
          image: "ithulasi/ccfms:1"
          imagePullPolicy: Always
          name: ccfms
          ports: 
#          - containerPort: 8081   
          - name: httpport
            containerPort: 9082
            hostPort: 9082      
          env:
            - name: ccfms.eureka.url
              value: "http://eureka:8761/eureka"  

              
                    